# Generated by Django 5.1.5 on 2025-02-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=200)),
                ('program_type', models.CharField(choices=[('learnership', 'Learnership'), ('internship', 'Internship'), ('skills_program', 'Skills Program')], max_length=20)),
                ('duration', models.PositiveIntegerField(help_text='Duration in months')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=15)),
            ],
        ),
    ]
