# Generated by Django 5.1.5 on 2025-02-02 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TrainingProgram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('certificate_number', models.CharField(max_length=50, unique=True)),
                ('offered_by', models.CharField(max_length=200)),
                ('training_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='TrainingProgram.trainingprogram')),
            ],
        ),
    ]
