# Generated by Django 5.1.5 on 2025-06-10 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TrainingProgram', '0002_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='programModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('title', models.TextField()),
                ('trainingProgram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TrainingProgram.trainingprogram')),
            ],
        ),
    ]
